server:
  port: 8080
spring:
  cloud:
    consul:
      discovery:
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 10s
      host: localhost
      port: 8500

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SECURITY_TOKEN_ISSUER}
heimdall:
  bifrost:
    security:
      oauth2:
        roles:
          role-management-read: READ:MANAGEMENT
          role-management-write: WRITE:MANAGEMENT
          role-management-configuration-set-read: READ:MANAGEMENT:CONFIGURATION-SET
          role-management-configuration-set-write: READ:MANAGEMENT:CONFIGURATION-SET
          role-management-suppression-entry-read: READ:MANAGEMENT:SUPPRESSION-ENTRIES
          role-management-suppression-entry-write: WRITE:MANAGEMENT:SUPPRESSION-ENTRY
          role-management-smtp-read: READ:MANAGEMENT:SMTP
          role-management-smtp-write: WRITE:MANAGEMENT:SMTP
        client:
          client-id: ${OAUTH_CLIENT_ID}

logging:
  level:
    org.springframework.security: TRACE
    com.heimdallauth.server.services: DEBUG